### ISSUE TITLE
tpcds generator fails to create 10tb (sf10000)'s store_returns table

### ISSUE THREAD

**Issue by findepi** [Teradata/tpcds#19]
Using presto's `tpcds` connector i run 
```
CREATE TABLE hive.tpcds_10tb_orc.store_returns WITH (format='ORC')  AS SELECT
  SR_RETURNED_DATE_SK, SR_RETURN_TIME_SK, SR_ITEM_SK, SR_CUSTOMER_SK,
  SR_CDEMO_SK, SR_HDEMO_SK, SR_ADDR_SK, SR_STORE_SK, SR_REASON_SK,
  SR_TICKET_NUMBER, SR_RETURN_QUANTITY, SR_RETURN_AMT, SR_RETURN_TAX,
  SR_RETURN_AMT_INC_TAX, SR_FEE, SR_RETURN_SHIP_COST, SR_REFUNDED_CASH,
  SR_REVERSED_CHARGE, SR_STORE_CREDIT, SR_NET_LOSS
FROM TPCDS.SF10000.STORE_RETURNS;
```

and the query failed with
```
java.lang.IllegalArgumentException: Year must be a positive value
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.teradata.tpcds.type.Date.<init>(Date.java:48)
	at com.teradata.tpcds.type.Date.fromJulianDays(Date.java:72)
	at com.teradata.tpcds.Scaling.getRowCountForDate(Scaling.java:142)
	at com.teradata.tpcds.Parallel.skipDaysUntilFirstRowOfChunk(Parallel.java:67)
	at com.teradata.tpcds.row.generator.StoreSalesRowGenerator.generateRowAndChildRows(StoreSalesRowGenerator.java:84)
	at com.teradata.tpcds.row.generator.StoreReturnsRowGenerator.generateRowAndChildRows(StoreReturnsRowGenerator.java:66)
	at com.teradata.tpcds.Results$ResultsIterator.computeNext(Results.java:116)
	at com.teradata.tpcds.Results$ResultsIterator.computeNext(Results.java:65)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.facebook.presto.tpcds.TpcdsRecordSet$TpcdsRecordCursor.advanceNextPosition(TpcdsRecordSet.java:116)
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:99)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:256)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:416)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:310)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:586)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:734)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Is it a numeric overflow problem? Is such big schema supported?

**Comment by findepi** [comment]
cc @ilfrin

**Comment by petroav** [comment]
It's most probably an overflow, yes. We can take a look next sprint as we're all booked up at the moment.

**Comment by petroav** [comment]
Fixed via https://github.com/Teradata/tpcds/pull/21. New release forthcoming.
